spring:
  application:
    name: auth-server
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: false
server:
  port: 7000
  servlet:
    context-path: '/hack/api'
