INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам Океанский пр-т, 34', '12:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам РКЦ Уссурийск', '12:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 ДГУ. Оплата за электроэнергию по тарифам с.Вл-Александровское, ул.Седова, 32', '12:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Коммунальные услуги (расходы прошлых лет)', '134.1000.05 ДГУ Оплата потребления электроэнергии с.В.Александровское,ул. Седова,32. Расходы прошлых лет.', '01:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Коммунальные услуги (расходы прошлых лет)', '134.1000.05 ДГУ Оплата потребления электроэнергии. Океанский пр-т,34. Расходы прошлых лет', '01:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Коммунальные услуги (расходы прошлых лет)', '134.1000.05 ДГУ Оплата потребления электроэнергии. РКЦ Уссурийск. Расходы прошлых лет', '01:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул.Колхозная 32б(склад)', '12:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7', '12:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Электроэнергия', '134.1000.01 Анадырь Оплата потребления электроэнергии ул. Дежнева,7 (дизель-генераторная установка)', '12:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '02:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '03:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '04:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '05:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '06:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '07:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '08:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '09:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '10:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '11:2022', null);
INSERT INTO cbr.prognoz (type_expenses, direction_expenses, date, sum) VALUES ('Отопление', '134.1000.02 Столовая ХБ Оплата за отопление по тарифам ул. М.Амурского, 42', '12:2022', null);
